from recipe.diagprm.prompts.doctor import (
    DOCTOR_SYSTEM_PROMPT,
    DOCTOR_SYSTEM_PROMPT_NO_KG,
    DOCTOR_FINAL_DIAGNOSIS_PROMPT,
)
from recipe.diagprm.prompts.patient import PATIENT_SYSTEM_PROMPT, PATIENT_OPENING_PROMPT
from recipe.diagprm.prompts.verifier import VERIFIER_SYSTEM_PROMPT

__all__ = [
    "DOCTOR_SYSTEM_PROMPT",
    "DOCTOR_SYSTEM_PROMPT_NO_KG",
    "DOCTOR_FINAL_DIAGNOSIS_PROMPT",
    "PATIENT_SYSTEM_PROMPT",
    "PATIENT_OPENING_PROMPT",
    "VERIFIER_SYSTEM_PROMPT",
]
